name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # O la rama que uses para producci√≥n, ej: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v3.0.1

      - name: 'Build and Deploy Backend'
        run: |-
          gcloud builds submit ./backend --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/conductor-backend
          gcloud run deploy conductor-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/conductor-backend \
            --platform managed \
            --region us-central1 \
            --set-env-vars "DB_NAME=${{ secrets.DB_NAME }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }}"

      - name: 'Build and Deploy Frontend'
        run: |-
          gcloud builds submit ./ProyIHC-MiniApp \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/conductor-frontend \
            --substitutions=_REACT_APP_API_URL="https://conductor-backend-${{ secrets.GCP_PROJECT_ID }}.us-central1.run.app",_REACT_APP_GOOGLE_MAPS_KEY="${{ secrets.REACT_APP_GOOGLE_MAPS_KEY }}"
          gcloud run deploy conductor-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/conductor-frontend \
            --platform managed \
            --region us-central1
